### ISSUE TITLE
Tumblr Login Failed

### ISSUE THREAD

**Issue by jalpa1234** [dakshsrivastava/Loglr#8]
Hello,

I am using 'com.daksh:loglr:1.2.1' dependency in my android application for tumblr login.

It works in other devices but when try to login Tumblr in "Moto g4 plus" device (Android OS 7.0) it always calls onLoginFailed listener.

Below is my stack trace:

09-07 17:53:08.124 4232-6796/com.oolotta W/DefaultRequestDirector: Authentication error: Unable to respond to any of these challenges: {oauth_consumer=WWW-Authenticate: Oauth_consumer realm="api", cookie=WWW-Authenticate: Cookie realm="web"}
09-07 17:53:08.125 4232-6796/com.oolotta W/System.err: oauth.signpost.exception.OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.
09-07 17:53:08.125 4232-6796/com.oolotta W/System.err:     at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:243)
09-07 17:53:08.125 4232-6796/com.oolotta W/System.err:     at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193)
09-07 17:53:08.126 4232-6796/com.oolotta W/System.err:     at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:74)
09-07 17:53:08.126 4232-6796/com.oolotta W/System.err:     at com.tumblr.loglr.TaskTumblrLogin.doInBackground(TaskTumblrLogin.java:152)
09-07 17:53:08.126 4232-6796/com.oolotta W/System.err:     at com.tumblr.loglr.TaskTumblrLogin.doInBackground(TaskTumblrLogin.java:34)
09-07 17:53:08.126 4232-6796/com.oolotta W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
09-07 17:53:08.126 4232-6796/com.oolotta W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-07 17:53:08.126 4232-6796/com.oolotta W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-07 17:53:08.126 4232-6796/com.oolotta W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-07 17:53:08.126 4232-6796/com.oolotta W/System.err:     at java.lang.Thread.run(Thread.java:761)
09-07 17:53:08.134 4232-4232/com.oolotta E/FA: Name must consist of letters, digits or _ (underscores). Type, name: event, Login Failed
09-07 17:53:08.134 4232-4232/com.oolotta W/System.err: com.tumblr.loglr.Exceptions.LoglrLoginException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.
09-07 17:53:08.135 4232-4232/com.oolotta W/System.err:     at com.tumblr.loglr.TaskTumblrLogin.doInBackground(TaskTumblrLogin.java:162)
09-07 17:53:08.135 4232-4232/com.oolotta W/System.err:     at com.tumblr.loglr.TaskTumblrLogin.doInBackground(TaskTumblrLogin.java:34)
09-07 17:53:08.135 4232-4232/com.oolotta W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
09-07 17:53:08.135 4232-4232/com.oolotta W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-07 17:53:08.135 4232-4232/com.oolotta W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-07 17:53:08.135 4232-4232/com.oolotta W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-07 17:53:08.135 4232-4232/com.oolotta W/System.err:     at java.lang.Thread.run(Thread.java:761)
09-07 17:53:08.139 4232-6721/com.oolotta D/FA: Logging event (FE): _err, Bundle[{_o=auto, _el=12, _ev=Login Failed, _sc=LoglrActivity, _si=4348724245434743105, _err=2}]
09-07 17:53:08.194 4232-6721/com.oolotta V/FA: Recording user engagement, ms: 1036
09-07 17:53:08.195 4232-6721/com.oolotta V/FA: Activity paused, time: 28381262
09-07 17:53:08.199 4232-6721/com.oolotta D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=1036, _sc=LoglrActivity, _si=4348724245434743105}]
09-07 17:53:08.237 4232-6721/com.oolotta V/FA: Activity resumed, time: 28381285
09-07 17:53:13.239 4232-6721/com.oolotta V/FA: Inactivity, disconnecting from the service

Please help...

**Comment by ArcherN9** [comment]
Hey jalpa1234. Thanks for bringing this in. I don't have Motorola phone to test this on my end. I'll see what I can do to rectify this.

From your stracktrace, I'm able to deduce that this is arising from the tokens never being sent across to Tumblr for OAuth. I'll look this up.

**Comment by SH4LIN** [comment]
It's working Fine in Other phone but in motorola phone i get com.tumblr.loglr.Exceptions.LoglrAPIException even after setting consumer key and consumer secret key

**Comment by rahuliyer95** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
youngqqcn, @gaiazov, @heypran, @lpyedge, @AntoBrajkovic, @samuelhmorgan, @liazheyua, @mvperez, @sunilvbanare, @jaydrozd, @vmateianu, @tonyqus, @Xcaciv, @BlankerL, @eyebolla, @lijuncq, @dz4va, @tommyliu9, @moregola, @nikkong

**Comment by rahuliyer95** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
guillaumechervetaxa, @luislopez-dev, @hassanselim0, @areebmajeed, @tanle8, @greysign, @WingHEX, @MegoyTambayan, @PuzzledAlien, @JoshCaravaggio, @maurocts, @levin9, @jaerith, @Mhmonicox, @arrebagrove, @weijing329, @MadSkittles, @Airwiwin, @Magomed26, @BitHighlander
