### ISSUE TITLE
NullPointerException on Login

### ISSUE THREAD

**Issue by sino123** [dakshsrivastava/Loglr#9]
Hi, 

I am facing an issue while trying to login, here is the output:

` java.lang.NullPointerException: Attempt to invoke virtual method 'android.webkit.WebSettings android.webkit.WebView.getSettings()' on a null object reference
                                                                           at com.tumblr.loglr.TaskTumblrLogin.onPostExecute(TaskTumblrLogin.java:203)
                                                                           at com.tumblr.loglr.TaskTumblrLogin.onPostExecute(TaskTumblrLogin.java:34)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:679)
                                                                           at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:696)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:150)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

any advice on here? Thanks!

**Comment by ArcherN9** [comment]
That's not nice. I'm in the process of moving this library to Kotlin. This NullPointer exception wont rise in that. I'll fix it and send an interim release anyway.

**Comment by ArcherN9** [comment]
Can you please share a case on how do I recreate the bug? I don't want to add a simple null check but handle the user flow appropriately. It'll help me to close this in a better fashion.

**Comment by sino123** [comment]
Well the login flow worked couple of times, suddenly I got the nullpointer. Is it possible that it has something to do wiht `WebStorage.deleteAllData()`? I used this method before for another case. 

Basically the issue comes up after calling the authorization process ` Loglr.getInstance()...` but `onLoginFailed` will not be called.

**Comment by ArcherN9** [comment]
I haven't done the root cause analysis yet. Though, I just uploaded v2.1.1. Try using that, see if you get a similar crash. I don't think you will since those are extinct on Kotlin. 

I'll check on `WebStorage.deleteAllData()` tomorrow.

**Comment by sino123** [comment]
Ok I updated gradle file with `compile 'com.daksh:loglr:2.1.1'` and tried to use   `Loglr.getInstance()...` in order to initiate login. But I cannot use this method anymore, just it gives me the possibility to use   `Loglr.Companion.getInstance()`. But when I run I get this exception: `java.lang.NoSuchFieldError: No static field activityTumblrAddressBar of type I in class Lcom/tumblr/loglr/R$id; or its superclasses (declaration of 'com.tumblr.loglr.R$id' appears in /data/app/com.myapp-2/base.apk:classes27.dex)`

Do I need to convert my Activity into Kotlin?

**Comment by ArcherN9** [comment]
Yes, you have to use `Loglr.Companion.getInstance()` if accessing the library from a java project. And no, you don't have to move to Kotlin. Kotlin and Java are interoperable so it ought to work just fine. But why do you get the `NoSuchFieldError`? I tried the login process multiple times with projects using Kotlin and without, it works fine every time. Are you using Proguard?

**Comment by sino123** [comment]
Ok I could fix it. The issue with `NoSuchFieldError `was because I used a layout name that is already defined in the library. Thank you for your fast fix!
